-   id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    args: ["--ignore-missing-imports", "--scripts-are-modules"]
    require_serial: true
    additional_dependencies: []

-   id: dmypy
    name: dmypy
    entry: dmypy run
    language: python
    types: [python]
    args: []
    require_serial: true
    additional_dependencies: []
